CREATE TABLE IF NOT EXISTS `#__virtuemart_shipment_plg_zasilkovna` (
	`id` int(1) unsigned NOT NULL AUTO_INCREMENT,
	`virtuemart_order_id` int(11) unsigned,
	`virtuemart_shipmentmethod_id` mediumint(1) unsigned,
	`order_number` char(32),
	`zasilkovna_packet_id` decimal(10,0),
	`zasilkovna_packet_price` decimal(15,2),
	`weight` decimal(10,4),
	`branch_id` decimal(10,0),
	`branch_currency` char(5),
	`branch_name_street` varchar(500),
	`is_carrier` smallint(1) NOT NULL DEFAULT '0',
	`carrier_pickup_point` varchar(40),
	`email` varchar(255),
	`phone` varchar(255),
	`first_name` varchar(255),
	`last_name` varchar(255),
	`address` varchar(255),
	`city` varchar(255),
	`zip_code` varchar(255),
	`virtuemart_country_id` varchar(255),
	`adult_content` smallint(1) DEFAULT '0',
	`is_cod` smallint(1),
	`packet_cod` decimal(15,2) DEFAULT '0.00',
	`exported` smallint(1),
	`printed_label` smallint(1) DEFAULT '0',
	`shipment_name` varchar(5000),
	`shipment_cost` decimal(10,2),
	`shipment_package_fee` decimal(10,2),
	`tax_id` smallint(1),
	`created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created_by` int(11) NOT NULL DEFAULT '0',
	`modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified_by` int(11) NOT NULL DEFAULT '0',
	`locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`locked_by` int(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='zasilkovna';

CREATE TABLE IF NOT EXISTS `#__virtuemart_zasilkovna_branches` (
	`id` int(10) NOT NULL,
	`name_street` varchar(200) NOT NULL,
	`currency` char(3) NOT NULL,
	`country` char(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
