<?php include __DIR__ . '/default.phtml'; ?>

<script>
    window.packetery.opcValidationCallback = function() {
        var selectedPoint = jQuery('input[name=virtuemart_shipmentmethod_id]:checked').closest('.zasilkovna_box').find('.picked-delivery-place');
        if(selectedPoint.length === 1 && !selectedPoint.text()) {
            alert(<?php echo json_encode($selectPickupPoint); ?>);
            return false;
        }

        return true;
    }

    addOpcTriggerer('callSubmitFunct', 'window.packetery.opcValidationCallback');
</script>
