<div class='zasilkovna_box'>
    <div class='zasilkovna_div'>
        <div class="zasilkovna_base">
        <?php echo $baseHtml; ?>
        </div>
        <?php if ($isCountrySelected) { ?>
        <div class='zas-box' style="display: none;">
            <div class='zasilkovna-logo'></div>
            <div class="zasilkovna-info">
                <a href='javascript:void(0)' class='open-packeta-widget'><?php echo htmlentities($selectPoint); ?></a>
                <iframe sandbox='allow-scripts allow-same-origin' allow='geolocation' class='packeta-widget'></iframe>
                <br>
                <ul><li><?php echo htmlentities($selectedPoint); ?>: <span class='picked-delivery-place'><?php echo htmlentities($savedBranchNameStreet); ?></span></li></ul>
            </div>
        </div>
        <?php } else { ?>
        <ul><li><?php echo htmlentities($enterAddress); ?></li></ul>
        <?php } ?>
    </div>
</div>
