<?php include __DIR__ . '/../tail-block-base.phtml'; ?>

<script>
    window.packetery.opcValidationCallback = function() {
        if(isPacketeryShippingSelected() && !isPacketeryShippingPointSelected()) {
            alert(<?php echo json_encode($selectPickupPoint); ?>);
            return false;
        }

        return true;
    }

    addOpcTriggerer('callSubmitFunct', 'window.packetery.opcValidationCallback');
</script>
